### ISSUE TITLE
Getting incompatability error on windows pc

### ISSUE THREAD

**Issue by slackteam** [taliesins/terraform-provider-hyperv#162]
When installing plugin in terraform on windows pc getting the following error.

│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/taliesins/hyperv v1.0.3 does not have a     
│ package available for your current platform, windows_386.

**Comment by taliesins** [comment]
I don't release a Win32 binary release for the provider, not sure if there is great demand for it. Have a look at https://github.com/taliesins/terraform-provider-hyperv/releases/tag/v1.0.4

You could attempt to download the code and compile it yourself. 

Might be helpful:
https://github.com/taliesins/terraform-provider-hyperv/blob/master/.goreleaser.yml#L16
https://goreleaser.com/cmd/goreleaser_build/
https://go.dev/doc/install/source#environment

**Comment by MT1ST** [comment]
Just following up here as I had mentioned in a fork of this Repo - for those of us encountering this error and getting their computer insisting that it's a 64-bit Windows, you may want to ensure that you have the `AMD64` version of Terraform downloaded, unzipped, and as part of the Path environment variable so that it comes up as your version. I had thought that using an Intel CPU, that it wouldn't necessarily work there, but it does work that way - and is not necessarily indicative of a 32-bit Windows installation. It might just mean that you have the wrong Terraform executable pulled down from here [ https://developer.hashicorp.com/terraform/install ].
