### ISSUE TITLE
401 Errors when applying

### ISSUE THREAD

**Issue by RespawnDespair** [taliesins/terraform-provider-hyperv#7]
Hello,

i would love to use Terraform to create some of our on-premise VM's in Hyper-V. Unfortunately i cannot pass my simple test below. Undoubtedly i have missed some important part in the setup.
Could somebody tell me what i'm doing wrong?

### Terraform Version
v0.11.11

### Affected Resource(s)
Please list the resources as a list, for example:
- hyperv_network_switch
- hyperv_vhd

(but probably all hyperv_ resources)

### Terraform Configuration Files
```hcl
# Configure HyperV
provider "hyperv" {
  user            = "terraform"
  password        = "<nope>"
  host            = "127.0.0.1"
  port            = 5985
  https           = false
  insecure        = false
  tls_server_name = ""
  cacert_path     = ""
  cert_path       = ""
  key_path        = ""
  script_path     = "C:/Temp/terraform_%RAND%.cmd"
  timeout         = "30s"
}

resource "hyperv_vhd" "web_server_vhd" {
  path = "D:\\environments\\vhdx\\packer-windows2016-1809-g2.vhdx"
  source_vm = "Windows2016"
}

resource "hyperv_network_switch" "dmz_network_switch" {
  name = "dmz"
}

resource "hyperv_machine_instance" "terraform_test" {
  name = "terraform_test"
  
  integration_services {
    "VSS" = true
  }

  network_adaptors {
    name = "wan"
    switch_name = "${hyperv_network_switch.dmz_network_switch.name}"
  }

  hard_disk_drives {
    path = "${hyperv_vhd.web_server_vhd.path}"
    controller_number = "0"
    controller_location = "0"
  }
}
```

### Debug Output
```
Error: Error applying plan:

2 error(s) occurred:

* hyperv_network_switch.dmz_network_switch: 1 error(s) occurred:

* hyperv_network_switch.dmz_network_switch: error uploading shell script: http response error: 401 - invalid content type
* hyperv_vhd.web_server_vhd: 1 error(s) occurred:

* hyperv_vhd.web_server_vhd: error uploading shell script: http response error: 401 - invalid content type

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Panic Output
not provided.

### Expected Behavior
I would have expected the VM to be created along with the network and switch.

### Actual Behavior
It gives the 401 problem.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
This happens when i run against my local Windows 10 Hyper-V and against a Windows 2012 R2 Server.
I don't have access to a Windows 2016 Server for testing right now...

**Comment by taliesins** [comment]
Can you run this again, but this time turn on terraform debug. https://www.terraform.io/docs/internals/debugging.html

**Comment by HolisticDeveloper** [comment]
From https://github.com/hashicorp/terraform/issues/2918 I found that the issue is with WinRM. You have to enable it for basic authentication per the readme at https://github.com/masterzen/winrm. It would be a good idea to put this into readme for this project.

**Comment by JustLeo** [comment]
Same here

**Comment by taliesins** [comment]
@RespawnDespair and @HolisticDeveloper I have improved the documentation to include how to setup http and https WinRM.

In addition I have added and defaulted to using NTLM for authentication, so its not really a requirement to use basic authentication anymore.

**Comment by SebTardif** [comment]
I'm using the latest of everything and I have the same problem. I wonder if someone know a simple sanity check, simple command to verify expectations.
`
...
2021-03-04T15:08:23.812-0500 [DEBUG] plugin.terraform-provider-hyperv_1.0.1: 2021/03/04 15:08:23 [INFO][hyperv][create] creating hyperv vhd:
...
2021-03-04T15:08:23.813-0500 [DEBUG] plugin.terraform-provider-hyperv_1.0.1: 2021/03/04 15:08:23 [DEBUG] Uploading shell wrapper for command from [/var/folders/2f/_cxrxpd109q313gtbnxvghfh0000gn/T/shell-terraform-1pJ5lWKks1A6LhtKDNA2KxeJsYQ.ps1002331892] to [$env:TEMP\shell-terraform-1pJ5lWKks1A6LhtKDNA2KxeJsYQ.ps1]
2021/03/04 15:08:23 [DEBUG] hyperv_vhd.web_server_vhd: apply errored, but we're indicating that via the Error pointer rather than returning it: error uploading shell script: http response error: 401 - invalid content type
`

But this work:

`
docker run -it mcr.microsoft.com/powershell:lts-centos-7
$username = "Administrator"
$password = "mypassword" # could be more secure, see https://stackoverflow.com/questions/6239647/using-powershell-credentials-without-being-prompted-for-a-password
$secstr = New-Object -TypeName System.Security.SecureString
$password.ToCharArray() | ForEach-Object {$secstr.AppendChar($_)}
$creds = new-object -typename System.Management.Automation.PSCredential -argumentlist $username, $secstr
$soptions = New-PSSessionOption -SkipCACheck -SkipCNCheck
Enter-PsSession –ComputerName 192.168.245.128 -Authentication Basic -Credential $creds -UseSSL -SessionOption $soptions
`

**Comment by amitky-vmw** [comment]
Hi - I still have the the issues with this.

**Comment by 0katrinpetrosyan0** [comment]
Hi I have problem with apply-ing also it says

`Error: checking for existing server1: error uploading shell script: http response error: 401 - invalid content type
│
│   with hyperv_machine_instance.server1,
│   on main.tf line 14, in resource "hyperv_machine_instance" "server1":
│   14: resource "hyperv_machine_instance" "server1" {`
