### ISSUE TITLE
Deplying VM on hyper-v server with running terraform on linux shell

### ISSUE THREAD

**Issue by TamarSa** [taliesins/terraform-provider-hyperv#72]
Hi

i am trying to understand how to deploy a vm on my hyper-v server using tf with no luck.
i am trying to run the terraform command from my local cmd on mac and i am guessing thats is the issue....should i only run it from the hyper-v powershell itself?

Thanks

**Comment by taliesins** [comment]
@TamarSa it should run fine from Linux or Mac. The way it works is that it remotely connects to a machine and send command via WinRM. Obviously if you run it on the same machine as the HyperV the remote location is 127.0.0.1 or what ever port WinRM is running on.

Most people seem to face difficulty in setting up WinRM to allow remote connections. Its either SSL issues or because you are domain joined and have things like policies causing issues.
